Repository sgammon/rules_graalvm, pull requests merged in 2023-09, with the labels that each got.

#70 fix(native_image): clean up construction of inputs
  internal/native_image/rules.bzl
Labels: enhancement

#76 fix: bcr tarball endpoint
  .bcr/source.template.json
  .github/workflows/on.release.yml
Labels: bug, bcr

#86 feat: bazel settings integration
  MODULE.bazel.lock
  README.md
  docs/api/defs.md
  docs/api/legacy.md
  docs/build-settings.md
  docs/index.md
  docs/shared-libraries.md
  example/integration_tests/bzlmod/MODULE.bazel.lock
  graal/graal.bzl
  graalvm/nativeimage/rules.bzl
  internal/conditions/BUILD.bazel
  internal/conditions/compiler/BUILD.bazel
  internal/conditions/tools/BUILD.bazel
  internal/native_image/builder.bzl
  internal/native_image/classic.bzl
  internal/native_image/common.bzl
  internal/native_image/rules.bzl
Labels: feature, native-image, 🚧 WIP

#101 fix: install requested components plus deps
  internal/graalvm_bindist.bzl
Labels: bug, components

#122 chore: issue fix release → `0.10.1`
  MODULE.bazel
  MODULE.bazel.lock
  README.md
  docs/index.md
Labels: bug, bcr

#132 fix(windows): added `use_param_file` for args
  internal/native_image/rules.bzl
Labels: bug, enhancement, platform:windows
